package br.edu.utfpr.ui.composite;

import java.util.List;

import org.vaadin.teemu.wizards.WizardStep;

import br.edu.utfpr.MyVaadinUI;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.Page;
import com.vaadin.server.ThemeResource;
import com.vaadin.server.VaadinRequest;
import com.vaadin.ui.Button;
import com.vaadin.ui.Component;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Image;
import com.vaadin.ui.Notification;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

public class TelaPergunta extends CustomComponent implements WizardStep {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Button btn;
	private OptionGroup opt;
	private List<String> respostas;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public TelaPergunta(String pergunta, List<String> respostas,
			String resource, VaadinRequest req, boolean isMulti) {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		this.respostas = respostas;
		setCaption(pergunta);

		setWidth("800px");
		setHeight("600px");
		// Label lbl = new
		// Label("<span style=\"font-size:20px;font-weigth:bold;  \"> " +
		// pergunta+"</span>" , ContentMode.HTML);
		// mainLayout.addComponent(lbl);

		// String url = Page.getCurrent().getLocation().getHost() + ":" +
		// Page.getCurrent().getLocation().getPort() +"/";

		Image img = new Image("", new ThemeResource(resource));
		img.setWidth("80%");

		// img.setHeight("200px");
		mainLayout.addComponent(img);

		// mainLayout.setExpandRatio(lbl, 1);
		mainLayout.setExpandRatio(img, 5);

		if (respostas != null) {

			opt = new OptionGroup();
			opt.setCaption("Respostas:");
			opt.setMultiSelect(isMulti);
			Panel p = new Panel(opt);
			for (String string : respostas) {
				opt.addItem(string);
			}
			p.setWidth("100%");
			p.setHeight("200px");
			mainLayout.addComponent(p);
			mainLayout.setExpandRatio(p, 1);

		}

	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("600px");

		// // top-level component properties
		// setWidth("100.0%");
		// setHeight("100.0%");

		// btn
		btn = new Button();
		btn.setCaption("Button");
		btn.setImmediate(true);
		btn.setWidth("-1px");
		btn.setHeight("-1px");

		return mainLayout;
	}

	@Override
	public Component getContent() {
		return this;
	}

	@Override
	public boolean onAdvance() {
		if (opt.getValue() != null) {

			if (opt.getValue().equals(respostas.get(2))) {
				MyVaadinUI.numAcertos++;
				Notification not = new Notification("Certo!",
						Notification.Type.HUMANIZED_MESSAGE);
				not.show(Page.getCurrent());

			}

			opt.setEnabled(false);

			// TODO Auto-generated method stub
			return true;
		} else {
			Notification.show("Informe uma resposta antes de prosseguir!",
					Notification.Type.WARNING_MESSAGE);
			return false;
		}
	}

	@Override
	public boolean onBack() {
		// TODO Auto-generated method stub
		return false;
	}

}
